CREATE DATABASE Restaurant_Management

USE Restaurant_Management

CREATE TABLE KHACHHANG
(
	MaKH varchar(10) PRIMARY KEY,
	HoTen varchar(25),
	SoDT varchar(20),
)

CREATE TABLE NHANVIEN
(
	MANV char(4) PRIMARY KEY,
	Hoten varchar(25),
	NgVL smalldatetime,
	ChucVu int,
	Luong money, 
)

CREATE TABLE BAN
(
	MABAN char(3) PRIMARY KEY,
	SOLUONG int,
	LOAIBAN bit,
	TINHTRANGBAN bit,
)

CREATE TABLE THUCDON
(
	MAMON varchar(10) PRIMARY KEY,
	TENMON varchar(30),
	DVT varchar(20),
	GIA money,
)

CREATE TABLE HOADON
(
	MAHD int PRIMARY KEY,
	MANV char(4),
	MAKH varchar(10),
	MABAN char(3),
	NGAYHD smalldatetime,
	TRIGIA money,
)

ALTER TABLE HOADON ADD CONSTRAINT FK_MANV 
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE HOADON ADD CONSTRAINT FK_MAKH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE HOADON ADD CONSTRAINT FK_MABAN
FOREIGN KEY (MABAN) REFERENCES BAN(MABAN)

CREATE TABLE CTHD
(
	MAHD int,
	MAMON varchar(10),
	SL int,
)

ALTER TABLE CTHD ADD CONSTRAINT FK_MAHD
FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CTHD ADD CONSTRAINT FK_MAMON
FOREIGN KEY (MAMON) REFERENCES THUCDON(MAMON)

CREATE TABLE TAIKHOAN
(
	MATK int PRIMARY KEY,
	HOTEN nvarchar(30) not null,
	MATKHAU nvarchar(20) not null,
	VAITRO bit not null --0: nhan vien, 1: quan ly
)